import type {
  ConfidenceLevel,
  CriticalityLevel,
  FrameworkSection,
  Requirement,
  Supplier,
  Weights,
} from './types'

export const confidenceLevels: ConfidenceLevel[] = [
  'Verified',
  'Estimated',
  'AI Suggested',
  'Needs Manual Review',
  'Unavailable Online',
]

export const criticalityLevels: CriticalityLevel[] = [
  'Low',
  'Medium',
  'High',
  'Critical',
]

export const defaultWeights: Weights = {
  landedCost: 20,
  tco: 15,
  leadTime: 15,
  capability: 15,
  qualityRisk: 15,
  geopoliticalRisk: 10,
  logistics: 5,
  contract: 5,
}

export const sampleRequirement: Requirement = {
  productName: 'Precision aluminum motor housing',
  productCategory: 'CNC machined components',
  productSpecs:
    '6061-T6 aluminum, anodized finish, +/-0.05 mm tolerance, RoHS compliant',
  quantity: 42000,
  qualityRequirements: 'PPAP sample approval, Cpk > 1.33, 100% dimensional report',
  complianceRequirements: 'RoHS, REACH, conflict minerals declaration',
  targetCost: 9.25,
  requiredLeadTime: 62,
  forecastedDemand: 168000,
  approvedMaterials: '6061-T6 aluminum, clear anodizing, approved insert hardware',
  technicalDrawings:
    'Drawing package GSC-MH-4821 Rev C; supplier NDA required before release',
  packagingRequirements: 'Tray packed, corrosion barrier bag, 240 units per pallet',
  deliveryLocation: 'Columbus, Ohio distribution center',
  criticality: 'High',
}

export const frameworkSections: FrameworkSection[] = [
  {
    id: 'cost',
    label: 'Cost',
    description: 'Direct landed cost inputs and cost-risk assumptions.',
    fields: [
      { key: 'unitCost', label: 'Unit cost', kind: 'currency' },
      { key: 'freightCost', label: 'Freight cost', kind: 'currency' },
      { key: 'tariffsDuty', label: 'Tariffs and duty', kind: 'currency' },
      { key: 'insurance', label: 'Insurance', kind: 'currency' },
      { key: 'customsBrokerage', label: 'Customs brokerage', kind: 'currency' },
      { key: 'packaging', label: 'Packaging', kind: 'currency' },
      { key: 'warehousing', label: 'Warehousing', kind: 'currency' },
      { key: 'costMoq', label: 'MOQ', kind: 'number' },
      { key: 'costPaymentTerms', label: 'Payment terms', kind: 'text' },
      { key: 'currencyRisk', label: 'Currency risk', kind: 'risk' },
      { key: 'qualityFailureCost', label: 'Quality failure cost', kind: 'currency' },
      { key: 'expediteCost', label: 'Expedite cost', kind: 'currency' },
      {
        key: 'inventoryHoldingCost',
        label: 'Inventory holding cost',
        kind: 'currency',
      },
      {
        key: 'supplierSwitchingCost',
        label: 'Supplier switching cost',
        kind: 'currency',
      },
    ],
  },
  {
    id: 'leadTime',
    label: 'Lead Time',
    description: 'End-to-end lead time assumptions in days.',
    fields: [
      {
        key: 'productionLeadTime',
        label: 'Supplier production lead time',
        kind: 'days',
      },
      { key: 'rawMaterialsLeadTime', label: 'Raw materials lead time', kind: 'days' },
      {
        key: 'supplierPlanningTime',
        label: 'Internal supplier planning time',
        kind: 'days',
      },
      { key: 'qualityInspectionTime', label: 'Quality inspection time', kind: 'days' },
      { key: 'exportClearanceTime', label: 'Export clearance time', kind: 'days' },
      { key: 'transitTime', label: 'Transit time', kind: 'days' },
      { key: 'customsClearanceTime', label: 'Customs clearance time', kind: 'days' },
      {
        key: 'receivingPutawayTime',
        label: 'Receiving and put-away time',
        kind: 'days',
      },
      { key: 'bufferTime', label: 'Buffer time', kind: 'days' },
      { key: 'reorderReviewCycle', label: 'Reorder review cycle', kind: 'days' },
    ],
  },
  {
    id: 'capability',
    label: 'Supplier Capability',
    description: 'Capability scores from 1 weak to 5 strong.',
    fields: [
      { key: 'volumeCapability', label: 'Volume capability score', kind: 'score' },
      { key: 'equipmentCapability', label: 'Equipment capability score', kind: 'score' },
      {
        key: 'qualityCertification',
        label: 'Quality certification score',
        kind: 'score',
      },
      { key: 'financialStability', label: 'Financial stability score', kind: 'score' },
      { key: 'scalingAbility', label: 'Scaling ability score', kind: 'score' },
      { key: 'engineeringSupport', label: 'Engineering support score', kind: 'score' },
      {
        key: 'complianceUnderstanding',
        label: 'Compliance understanding score',
        kind: 'score',
      },
      {
        key: 'documentationAbility',
        label: 'Documentation ability score',
        kind: 'score',
      },
      {
        key: 'singleFactoryDependency',
        label: 'Single factory dependency score',
        kind: 'score',
      },
      { key: 'backupCapacity', label: 'Backup capacity score', kind: 'score' },
    ],
  },
  {
    id: 'qualityRisk',
    label: 'Quality Risk',
    description: 'Risk scores from 1 very low risk to 5 very high risk.',
    fields: [
      { key: 'defectRateRisk', label: 'Defect rate score', kind: 'risk' },
      { key: 'processControlRisk', label: 'Process control score', kind: 'risk' },
      { key: 'inspectionMethodRisk', label: 'Inspection method score', kind: 'risk' },
      { key: 'certificationRisk', label: 'Certification score', kind: 'risk' },
      { key: 'traceabilityRisk', label: 'Traceability score', kind: 'risk' },
      { key: 'correctiveActionRisk', label: 'Corrective action score', kind: 'risk' },
      { key: 'auditResultRisk', label: 'Audit result score', kind: 'risk' },
      {
        key: 'warrantyClaimRisk',
        label: 'Warranty claim risk score',
        kind: 'risk',
      },
      { key: 'returnRateRisk', label: 'Return rate risk score', kind: 'risk' },
      {
        key: 'fieldFailureRisk',
        label: 'Field failure risk score',
        kind: 'risk',
      },
    ],
  },
  {
    id: 'geopoliticalRisk',
    label: 'Geopolitical Risk',
    description: 'Country and trade exposure scores from 1 low to 5 high.',
    fields: [
      { key: 'tradeWarExposure', label: 'Trade war exposure', kind: 'risk' },
      { key: 'tariffRisk', label: 'Tariff risk', kind: 'risk' },
      { key: 'exportControlRisk', label: 'Export control risk', kind: 'risk' },
      { key: 'sanctionsRisk', label: 'Sanctions risk', kind: 'risk' },
      {
        key: 'politicalInstabilityRisk',
        label: 'Political instability risk',
        kind: 'risk',
      },
      { key: 'militaryConflictRisk', label: 'Military conflict risk', kind: 'risk' },
      { key: 'portDisruptionRisk', label: 'Port disruption risk', kind: 'risk' },
      { key: 'laborStrikeRisk', label: 'Labor strike risk', kind: 'risk' },
      {
        key: 'currencyInstabilityRisk',
        label: 'Currency instability risk',
        kind: 'risk',
      },
      {
        key: 'governmentPolicyRisk',
        label: 'Government policy risk',
        kind: 'risk',
      },
      {
        key: 'singleCountryDependencyRisk',
        label: 'Single country dependency risk',
        kind: 'risk',
      },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics Complexity',
    description: 'Logistics and import complexity scores from 1 low to 5 high.',
    fields: [
      { key: 'incotermsComplexity', label: 'Incoterms complexity', kind: 'risk' },
      { key: 'oceanFreightRisk', label: 'Ocean freight risk', kind: 'risk' },
      { key: 'airFreightRisk', label: 'Air freight risk', kind: 'risk' },
      { key: 'portCongestionRisk', label: 'Port congestion risk', kind: 'risk' },
      {
        key: 'containerAvailabilityRisk',
        label: 'Container availability risk',
        kind: 'risk',
      },
      {
        key: 'customsClearanceComplexity',
        label: 'Customs clearance complexity',
        kind: 'risk',
      },
      {
        key: 'freightForwarderRequirement',
        label: 'Freight forwarder requirement',
        kind: 'risk',
      },
      { key: 'thirdPartyLogisticsRequirement', label: '3PL requirement', kind: 'risk' },
      { key: 'warehousingRequirement', label: 'Warehousing requirement', kind: 'risk' },
      {
        key: 'crossDockingRequirement',
        label: 'Cross-docking requirement',
        kind: 'risk',
      },
      { key: 'lastMileComplexity', label: 'Last-mile complexity', kind: 'risk' },
      {
        key: 'importDocumentationRisk',
        label: 'Import documentation risk',
        kind: 'risk',
      },
      { key: 'hsCodeRisk', label: 'HS code risk', kind: 'risk' },
      { key: 'dutiesTaxesRisk', label: 'Duties and taxes risk', kind: 'risk' },
    ],
  },
  {
    id: 'contract',
    label: 'Contract Terms',
    description: 'Commercial terms and contract quality assumptions.',
    fields: [
      { key: 'contractPaymentTerms', label: 'Payment terms', kind: 'text' },
      { key: 'contractMoq', label: 'MOQ', kind: 'number' },
      { key: 'volumeDiscounts', label: 'Volume discounts', kind: 'text' },
      {
        key: 'priceAdjustmentClause',
        label: 'Price adjustment clause',
        kind: 'score',
      },
      {
        key: 'leadTimeCommitment',
        label: 'Lead time commitment',
        kind: 'score',
      },
      { key: 'serviceLevelAgreement', label: 'Service level agreement', kind: 'score' },
      { key: 'warrantyTerms', label: 'Warranty terms', kind: 'score' },
      { key: 'liabilityTerms', label: 'Liability terms', kind: 'score' },
      { key: 'penalties', label: 'Penalties', kind: 'score' },
      { key: 'contractIncoterms', label: 'Incoterms', kind: 'text' },
      { key: 'ipProtection', label: 'IP protection', kind: 'score' },
      { key: 'terminationClause', label: 'Termination clause', kind: 'score' },
      { key: 'exclusivity', label: 'Exclusivity', kind: 'risk' },
      { key: 'capacityReservation', label: 'Capacity reservation', kind: 'score' },
      { key: 'forecastCommitments', label: 'Forecast commitments', kind: 'risk' },
    ],
  },
]

const commonValues: Supplier['values'] = {
  unitCost: 8.8,
  freightCost: 0.9,
  tariffsDuty: 0.6,
  insurance: 0.1,
  customsBrokerage: 0.08,
  packaging: 0.18,
  warehousing: 0.14,
  costMoq: 25000,
  costPaymentTerms: 'Net 45',
  currencyRisk: 2,
  qualityFailureCost: 0.22,
  expediteCost: 0.18,
  inventoryHoldingCost: 0.3,
  supplierSwitchingCost: 0.16,
  productionLeadTime: 28,
  rawMaterialsLeadTime: 14,
  supplierPlanningTime: 4,
  qualityInspectionTime: 3,
  exportClearanceTime: 2,
  transitTime: 24,
  customsClearanceTime: 4,
  receivingPutawayTime: 2,
  bufferTime: 7,
  reorderReviewCycle: 14,
  volumeCapability: 4,
  equipmentCapability: 4,
  qualityCertification: 4,
  financialStability: 4,
  scalingAbility: 4,
  engineeringSupport: 4,
  complianceUnderstanding: 4,
  documentationAbility: 4,
  singleFactoryDependency: 3,
  backupCapacity: 3,
  defectRateRisk: 2,
  processControlRisk: 2,
  inspectionMethodRisk: 2,
  certificationRisk: 2,
  traceabilityRisk: 2,
  correctiveActionRisk: 2,
  auditResultRisk: 2,
  warrantyClaimRisk: 2,
  returnRateRisk: 2,
  fieldFailureRisk: 2,
  tradeWarExposure: 2,
  tariffRisk: 2,
  exportControlRisk: 2,
  sanctionsRisk: 1,
  politicalInstabilityRisk: 2,
  militaryConflictRisk: 1,
  portDisruptionRisk: 3,
  laborStrikeRisk: 2,
  currencyInstabilityRisk: 2,
  governmentPolicyRisk: 2,
  singleCountryDependencyRisk: 3,
  incotermsComplexity: 2,
  oceanFreightRisk: 3,
  airFreightRisk: 2,
  portCongestionRisk: 3,
  containerAvailabilityRisk: 2,
  customsClearanceComplexity: 2,
  freightForwarderRequirement: 2,
  thirdPartyLogisticsRequirement: 2,
  warehousingRequirement: 2,
  crossDockingRequirement: 1,
  lastMileComplexity: 2,
  importDocumentationRisk: 2,
  hsCodeRisk: 2,
  dutiesTaxesRisk: 2,
  contractPaymentTerms: 'Net 45 after inspection',
  contractMoq: 25000,
  volumeDiscounts: '2% over 75k units',
  priceAdjustmentClause: 4,
  leadTimeCommitment: 4,
  serviceLevelAgreement: 4,
  warrantyTerms: 4,
  liabilityTerms: 3,
  penalties: 3,
  contractIncoterms: 'FOB Hai Phong',
  ipProtection: 4,
  terminationClause: 4,
  exclusivity: 2,
  capacityReservation: 3,
  forecastCommitments: 2,
}

export const sampleSuppliers: Supplier[] = [
  {
    id: 'pacific-precision',
    name: 'Pacific Precision Manufacturing',
    country: 'Vietnam',
    region: 'Southeast Asia',
    website: 'https://example.com/pacific-precision',
    productMatch: 'Strong CNC aluminum housing capability',
    certifications: 'ISO 9001, IATF 16949, RoHS process controls',
    annualCapacity: 220000,
    customerNotes: 'Verified through sourcing database and prior RFQ packet.',
    confidenceLevel: 'Verified',
    values: {
      ...commonValues,
      unitCost: 8.45,
      freightCost: 0.82,
      tariffsDuty: 0.48,
      inventoryHoldingCost: 0.28,
      productionLeadTime: 30,
      transitTime: 22,
      bufferTime: 6,
      volumeCapability: 5,
      scalingAbility: 4,
      engineeringSupport: 4,
      backupCapacity: 4,
      geopoliticalRiskAverage: 2,
      portCongestionRisk: 2,
      contractPaymentTerms: 'Net 60 after PPAP approval',
      contractMoq: 30000,
      capacityReservation: 4,
    },
  },
  {
    id: 'shenzhen-alloy',
    name: 'Shenzhen Alloy Works',
    country: 'China',
    region: 'East Asia',
    website: 'https://example.com/shenzhen-alloy',
    productMatch: 'Excellent machining breadth, tariff exposure needs review',
    certifications: 'ISO 9001; IATF data pending',
    annualCapacity: 340000,
    customerNotes: 'Pricing attractive, but certification data needs manual validation.',
    confidenceLevel: 'Needs Manual Review',
    values: {
      ...commonValues,
      unitCost: 7.92,
      freightCost: 0.95,
      tariffsDuty: 1.1,
      customsBrokerage: 0.11,
      costMoq: 40000,
      costPaymentTerms: '30% deposit / 70% before shipment',
      currencyRisk: 3,
      qualityFailureCost: 0.36,
      supplierSwitchingCost: 0.22,
      productionLeadTime: 24,
      rawMaterialsLeadTime: 12,
      transitTime: 26,
      bufferTime: 9,
      qualityCertification: 3,
      complianceUnderstanding: 3,
      documentationAbility: 3,
      defectRateRisk: 3,
      certificationRisk: 4,
      traceabilityRisk: 3,
      auditResultRisk: 3,
      tradeWarExposure: 4,
      tariffRisk: 4,
      exportControlRisk: 3,
      governmentPolicyRisk: 3,
      singleCountryDependencyRisk: 4,
      dutiesTaxesRisk: 4,
      contractPaymentTerms: '30% deposit, balance before shipment',
      contractMoq: 40000,
      volumeDiscounts: '4% over 120k units',
      liabilityTerms: 2,
      ipProtection: 3,
      forecastCommitments: 3,
    },
  },
  {
    id: 'monterrey-cnc',
    name: 'Monterrey CNC Partners',
    country: 'Mexico',
    region: 'North America',
    website: 'https://example.com/monterrey-cnc',
    productMatch: 'Nearshore option with faster transit and higher unit cost',
    certifications: 'ISO 9001, IATF 16949, USMCA documentation',
    annualCapacity: 145000,
    customerNotes: 'Estimated cost from benchmark quote. Strong logistics profile.',
    confidenceLevel: 'Estimated',
    values: {
      ...commonValues,
      unitCost: 9.35,
      freightCost: 0.42,
      tariffsDuty: 0.08,
      insurance: 0.06,
      customsBrokerage: 0.06,
      warehousing: 0.08,
      costMoq: 15000,
      qualityFailureCost: 0.18,
      expediteCost: 0.08,
      inventoryHoldingCost: 0.16,
      productionLeadTime: 20,
      rawMaterialsLeadTime: 10,
      exportClearanceTime: 1,
      transitTime: 5,
      customsClearanceTime: 2,
      bufferTime: 4,
      reorderReviewCycle: 7,
      volumeCapability: 3,
      scalingAbility: 3,
      backupCapacity: 3,
      defectRateRisk: 2,
      processControlRisk: 2,
      warrantyClaimRisk: 1,
      tradeWarExposure: 1,
      tariffRisk: 1,
      exportControlRisk: 1,
      portDisruptionRisk: 1,
      currencyInstabilityRisk: 3,
      singleCountryDependencyRisk: 2,
      incotermsComplexity: 1,
      oceanFreightRisk: 1,
      portCongestionRisk: 1,
      freightForwarderRequirement: 1,
      importDocumentationRisk: 1,
      dutiesTaxesRisk: 1,
      contractPaymentTerms: 'Net 30 after receipt',
      contractMoq: 15000,
      leadTimeCommitment: 5,
      serviceLevelAgreement: 4,
      penalties: 4,
      contractIncoterms: 'DAP Columbus',
      capacityReservation: 3,
      forecastCommitments: 2,
    },
  },
]
